[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "biophysics"
authors = [{name = "Pachter Lab", email = "https://github.com/pachterlab"}]
dynamic = ["version", "description"]
